### ISSUE TITLE
Definir fundamentos del diseño 

### ISSUE THREAD

**Issue by NicolasGF-Boot** [jefraroce/bit-video-gui#1]
(librería de iconos, colores, fuente, tamaño de fuente)

**Comment by ccal-2** [comment]
[estilos cinema css.txt](https://github.com/jefraroce/bit-video-gui/files/4726783/estilos.cinema.css.txt)
[Guia de estilos para BIT video.pdf](https://github.com/jefraroce/bit-video-gui/files/4726784/Guia.de.estilos.para.BIT.video.pdf)

**Comment by ccal-2** [comment]
https://github.com/ccal-2/bit_video
